import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import Image from 'next/image'
import Profile from "../../public/images/profile/profile.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from '@/components/TransitionEffect'
import React, {useState} from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [modal, setModal] = useState(false)
  const [name, setName] = useState("")
  const [email, setEmail] = useState("")
  const [message, setMessage] = useState("")

  const handleModal = (e) => {
    
    setModal(!modal)
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    
    try {
      const response = await axios.post(`/api/NotionForm`, {
        name, 
        email,
        message
      })
      alert("Thank You! I will get back to you as soon as possible.")
      setName("")
      setEmail("")
      setMessage("")


    } catch (error) {
      console.error('error')
    }
  }

  return (
    <>
      <Head>
        <title>Brians Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TransitionEffect />

      <main className="flex items-center text-dark w-full min-h-screen">
          <Layout className="pt-0 md:pt-16 sm:pt-8">
            <div className="flex items-center justify-between w-full lg:flex-col">
              <div className="w-1/2 md:w-full">
              <Image
              src={Profile}
              alt="Profile Image"
              className="w-full h-auto lg:hidden md:inline-block md:w-full "
              priority
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
              </div>

              <div className='w-1/2 flex flex-col items-center self-center ml-12'>
                <AnimatedText text="Turning Vision Into Reality With Code And Design." className="!text-6xl !text-left" />
                <p className="my-4 text-base font-medium">
                As a full-stack developer, I am dedicated to turning ideas into innovative web applications and mobile apps. 
                Explore my latest projects, showcasing my expertise in web development, mobile development, and full stack projects.
                </p>

                <div className="flex items-center self-start mt-2">
                  <Link href="/Brian's Resume.pdf" 
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark
                  md:p-2 md:px-4 md:text-base
                  "
                  download={true}
                  >Resume <LinkArrow className="w-6 ml-1" /> </Link>
                  {/* <button  onClick={handleModal} className="ml-4 text-lg font-medium capitalize text-dark underline">Contact Me</button> */}
                </div>

                

                <form onSubmit={handleSubmit}  className={modal ? "p-12 absolute top-[30%] right-[20%] z-100 h-1/3 w-1/2 bg-cyan-800 rounded-xl" : "hidden"}>
                  <label className="flex flex-col gap-y-2 text-light">
                    Your Name
                    <input 
                      type="text" 
                      placeholder="Fill in your name here"
                      className="border-2 rounded-md p-2 text-dark"
                      value={name}
                      onChange={(e) => setName(e.target.value)}
                      required
                    />
                  </label>

                  <label className="flex flex-col gap-y-2 my-4 text-light">
                    Your Email
                    <input 
                      type="email" 
                      placeholder="Fill in your email address here"
                      className="border-2 rounded-md p-2 text-dark"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      required
                    />
                  </label>

                  <label className="flex flex-col gap-y-2 my-4 text-light">
                    Your Message
                    <input 
                      type="text" 
                      placeholder="What you want to say?"
                      className="border-2 rounded-md p-2 text-dark"
                      value={message}
                      onChange={(e) => setMessage(e.target.value)}
                    />
                  </label>
                  <div className="flex justify-center items-center pt-5 gap-6">
                  <button type="submit" className="border-2 border-light p-2 rounded-md text-light hover:bg-dark">Submit</button>
                  <button onClick={handleModal} className="border-2 border-light p-2 rounded-md text-light hover:bg-dark">Close</button>
                  </div>
                </form>

              </div>

              
            </div>

            
          </Layout>

          <HireMe modal={modal} />
          <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
            <Image src={lightBulb} alt="" className="w-full h-auto" />
          </div>
      </main>
    </>
  )
}
